[[MGARD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e77c13f812d472cbe3dd3d820305dee5f3f97010"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "496f21808975d3eb4aff44f0a29d6c312202025195d8ce91c08518736723762c"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51fb885e4a73122d48bcd11e9c282d45848b7df6"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "0f1625886f358d4482465ae4052f846570e2122cd01ce87de43e6f6c8bfd439f"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[MGARD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ed8cf12971f37ec0b1d9aa71910f58f677191d3"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "0fa1d77d929f942300f91eb46047c72fc8d705524d23b30bef3c0ab05d1c246e"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MGARD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d09ab4a0eb87c1827141f7b20b9a921f567ce8d"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "c81314e702fc3e8acf720b0127aeb4f528b7917eae15df89059615b26955562a"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MGARD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2813ae8c36488229295e4e3bc3d2001d5cd59242"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "2655b7e924e9b519f6753cc34ad371d9eab10251454f738ab0aed5199727b02f"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MGARD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f43ed61234218e94efb9d60ada2b41919bf0e40f"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "98424fbd48d292bdfaf0026964347188c2cf232d8833fc8f2ec62f6d6cf5ac97"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MGARD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "74fe431b4d735d1de3b63662afbaa2fd9f0311e5"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "d9cb9116a106d5549d6d6a114954a57b6d70a7a1bac7d19622365d9ea2978eeb"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.i686-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "452dc18cc33f8ff7bda6371a4e526b599afa502e"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "af2d93703a1e75fa03ec98f8fd4efc87afb6df8d843ef825d5364df9c7ff9c98"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.i686-linux-musl-cxx11.tar.gz"
[[MGARD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5a052e85327a90c49953758b37574d38e8f75af"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "d778c000d76e55621e7429aba936e04cded7683695775dd40f36080c1ff75baa"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "942fa07d3ec6feca89ca487fa9623910c5aea862"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "edebc9cd93cf1c454e79ff55044a959b0f217248ea313afc8e137a5059571ca4"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.riscv64-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adf494d0c7437c4bd44f226e3e6ca176a604f7e3"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "675b65ef2a772fbb8279b71ac3ede725bca02ad1324ad62e49bd9fb4de843c5b"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e5bb32ac50c7656755aa6fb99a72f9939bd8447"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "888f51ebe7818c92bdc4c88c7ea1f45c48c1155111fa1781b1e67ae7ba6e5171"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+0/MGARD.v1.6.0.x86_64-linux-musl-cxx11.tar.gz"
