[[MGARD]]
arch = "aarch64"
git-tree-sha1 = "f12c5f2a3d66f187ecd6940dc29516353f33caa6"
os = "macos"

    [[MGARD.download]]
    sha256 = "3cf34844af4e05fc40edaf58abd92dd2c5afd38f38588704e3ce31cef3c3bd16"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.aarch64-apple-darwin.tar.gz"
[[MGARD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a959822cc964f79d9701d9601f62f47c6418725"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "b124fb0ee54b3a2b37e3c5c0ca2ad21d99a43e1a7fa62be1bb06d7e84f4ebf97"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.aarch64-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8335997973374dc854426747dc8d92a1d8bd26b6"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "6dc3671983ac0be8d9be7be0d763019b8d1883719a843aff073733eb58fcb935"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.aarch64-linux-musl-cxx11.tar.gz"
[[MGARD]]
arch = "aarch64"
git-tree-sha1 = "5e0c78970cf6a96a5ed96321890c5012d3b7d15a"
os = "freebsd"

    [[MGARD.download]]
    sha256 = "6893f5fda92880a3ff363af8334594b80f7c6a318c8a8a3206257e47c3cc5ba3"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.aarch64-unknown-freebsd.tar.gz"
[[MGARD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "100df8c8e6e1fe04153c2117fde8ffa6511f63f5"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "ade406d12727c824c927f699a1936bf7783f52d8f9eb87c9a2770588e7b7da85"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MGARD]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "906f47f41f740ecdd6a861e77dd4ac54d3666afe"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "fe5945f971543df01f2a1ea3363c67ecd8fd9ecc8b20961a39e2b2176afff379"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MGARD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d18e53277291446061df38f9673b428635bbe34a"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "f91caa09b3375d6a403792936fc7a9b3737616599de4786602a7208ef8147b04"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MGARD]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a01129a15c22fec3c00b92263acc37fba66ad8f1"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "c6d0a655a3cc86b9fa9c5f6b950466c2c0f774dcc16e78fa13bf540b788141d3"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MGARD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b853ad30b7e601704ec5d1bd5371aec19df32603"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "21db64895cdb4ac43d23060adedd3d9ba994a12cb3fcae6943e7fc3f1c7d8190"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.i686-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a99a3b90253f971ef7e473f642e2aae6e608c9db"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "5dace3beed2ec26f1855136abbfcb4788b5fa8a101514d64d6cefe4841485fe9"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.i686-linux-musl-cxx11.tar.gz"
[[MGARD]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c28bddfd7a5fbc393664b3ddf7b1c83d307732a"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "4b4c3e6b6dc40c0fecb52165e5781c2cd02a723dc1826cdd259b4b4e978e744e"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0216973169e7efa16dbffd15eebc8aaaf1cdcbf2"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "84f5a968e193aeffbe7cd8dd2bef41127b77df391d4f0316930ef99e67d17358"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.riscv64-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "x86_64"
git-tree-sha1 = "e24925844a2b05a639a051c7b767a207e4f023de"
os = "macos"

    [[MGARD.download]]
    sha256 = "a4c2117abb262ff410ac5628b5f546a909fdabec0b71acfcc7d702d5763230df"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.x86_64-apple-darwin.tar.gz"
[[MGARD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43cf87ef507e55806aee2240416fa8f31ca51e8f"
libc = "glibc"
os = "linux"

    [[MGARD.download]]
    sha256 = "f31a6487538f94573804b55c943fd3075a2e0ba27c868786cd44b66d0a5990c6"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.x86_64-linux-gnu-cxx11.tar.gz"
[[MGARD]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee4dd7a57685c6f2262b3a2bccafc4b60cfed25f"
libc = "musl"
os = "linux"

    [[MGARD.download]]
    sha256 = "9634df50a809a603939c81537b5923c33d31aa954e70610648c91ba3f660bfc8"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.x86_64-linux-musl-cxx11.tar.gz"
[[MGARD]]
arch = "x86_64"
git-tree-sha1 = "0720cad34932fdf04ba0f8e27b5f70f9d97c0de0"
os = "freebsd"

    [[MGARD.download]]
    sha256 = "05eac19c37e7333239330feefdae0f19299b420cfa16367cb3f5dbafaa376f19"
    url = "https://github.com/JuliaBinaryWrappers/MGARD_jll.jl/releases/download/MGARD-v1.6.0+1/MGARD.v1.6.0.x86_64-unknown-freebsd.tar.gz"
